apiVersion: v1
entries:
  helm-chart:
  - apiVersion: v2
    appVersion: 1.2.3
    created: "2025-01-16T06:21:48.541438164Z"
    digest: 42f5ed6dd7c9eb48d6a4004c1df05d2695e73e6c73eaa5156fd375658f1e0ca9
    home: https://kimjeongjun08.github.io/charts-practice/index.yaml
    name: helm-chart
    urls:
    - https://kimjeongjun08.github.io/chart-practice/charts/helm-chart-1.2.3.tgz
    version: 1.2.3
generated: "2025-01-16T06:21:48.540903322Z"
